namespace Crm.Domain.Enums;

public enum AuditAction
{
    OpportunityCreated = 1,
    OpportunityUpdated = 2,
    StatusChanged = 3,
    StageChanged = 4,
    GateOpened = 5,
    GateApproved = 6,
    GateRejected = 7,
    GateReturned = 8,
    NoteAdded = 9,
    NoteEdited = 10,
    CommentAdded = 11,
    CommentEdited = 12,
    CommentDeleted = 13,
    AttachmentUploaded = 14,
    AttachmentDeleted = 15,
    AttachmentDownloaded = 16,
    BuilderAssigned = 17,
    DeadlinesSet = 18,
    EstimatedCostSubmitted = 19,
    BidBondRequested = 20,
    BidBondIssued = 21,
    ProposalSubmittedForReview = 22,
    ProposalReturned = 23,
    ApprovalRequested = 24,
    Submitted = 25,
    OutcomeRecorded = 26,
    ContractStageChanged = 27,
    OpportunityHeld = 28,
    OpportunityResumed = 29,
    OpportunityCanceled = 30,
    EmailGenerated = 31,
    EmailSent = 32,
    UserLoggedIn = 33,
    AccessDenied = 34
}
